// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using tilrepo.Models;

namespace tilrepo.Migrations
{
    [DbContext(typeof(tilRepoContext))]
    [Migration("20171119165135_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("tilrepo.Models.til", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("addedOn");

                    b.Property<string>("content");

                    b.Property<string>("reference");

                    b.Property<string>("tags");

                    b.HasKey("id");

                    b.ToTable("til");
                });
#pragma warning restore 612, 618
        }
    }
}
